// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4wsqeBUEj0OSDVmFGVDogGwXFjQYbTqU',
    appId: '1:533540273573:web:5bd10554b47cca96d13c4c',
    messagingSenderId: '533540273573',
    projectId: 'financy-c26b8',
    authDomain: 'financy-c26b8.firebaseapp.com',
    storageBucket: 'financy-c26b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsb1Q-iDxdxKTx9Mg0urC6XzQIY0Y09Vw',
    appId: '1:533540273573:android:efe897ad6554ba83d13c4c',
    messagingSenderId: '533540273573',
    projectId: 'financy-c26b8',
    storageBucket: 'financy-c26b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7I7nxRX9-TMxnF2Gv5NQmOAyzoS16V_k',
    appId: '1:533540273573:ios:af29f7b4c7075e86d13c4c',
    messagingSenderId: '533540273573',
    projectId: 'financy-c26b8',
    storageBucket: 'financy-c26b8.appspot.com',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4wsqeBUEj0OSDVmFGVDogGwXFjQYbTqU',
    appId: '1:533540273573:web:237bbb91ab67be80d13c4c',
    messagingSenderId: '533540273573',
    projectId: 'financy-c26b8',
    authDomain: 'financy-c26b8.firebaseapp.com',
    storageBucket: 'financy-c26b8.appspot.com',
  );
}
